opensourcerouting/frr

redhat/frr.spec.in

`systemctl' returns different, non-useful output while in a chroot.
Switch to checking if /sbin/init is a symlink to the systemd binary.
With this change the build works in a mock chroot.
Signed-off-by: Silas McCroskey <smccroskey@cumulusnetworks.com>

redhat: use %initsystem check that works when chrooted

---

pathd/path_pcep_lib.c

Fix for pcep counters show with null session
- also fixed a few minor compilation warnings

Fix for pcep counters show with null session

---

pathd/path_pcep.c
pathd/path_pcep_controller.c
pathd/path_pcep_debug.c
pathd/path_pcep_lib.c
pathd/path_pcep_pcc.c

- I forgot to run clang formatting on the previous
patch, so here are the formatting fixes.

CLANG Formatting changes for previous patch

---

pathd/path_pcep.c
pathd/path_pcep.h
pathd/path_pcep_lib.c
vtysh/vtysh.c

Now MSD (Maximum SID Depth) is not sended to remote PCE in open message, fix that taking value from configuration even the ideally feature is getting from isis (which should be a future fix).
Both PCE tested (Cisco and ODL) requires flag `sr-draft07` in pce configuration for the MSD value to be processed.
It's been tested 
1. In cisco it's been checked with `show pce ipv4 peer detail` 
2. In ODL with karaf log (`log:set DEBUG`)

New config parameter (msd) in pcc configuration

---

pathd/path_pcep_lib.c
pathd/path_pcep_lib.h
pathd/path_pcep_pcc.c

- They should be rejected if the PCEP session is PCC initiated,
since they are only supported for PCE initiated PCEP sessions.

Reject unsupported PcInitate PCEP messages

---

pathd/path_pcep_pcc.c

- Previously, if multiple PCE configurations are received
but the configuration is the same, pathd would disconnect
from the PCE and connect again.

Check for duplicate configuration before disconnecting

---

pathd/path_pcep_nb.c

If the PCE detect that a link part of the lsp has been lost ( down, etc) then sends a PcUpd to the PCC with the new status that will be end up in an inactive sr policy
Signed-off-by: Javier Garcia <javier.garcia@voltanet.io>

Delete candidate when segment list name is empty

---

pathd/path_pcep_controller.c
pathd/path_pcep_controller.h
pathd/path_pcep_debug.c
pathd/path_pcep_lib.c

- Instead, provide a callback that when called, will create
an FRR thread event. This event callback will then handle
the pceplib pcep_event

Do not poll pceplib pcep_events anymore

---

pathd/path_pcep_controller.c
pathd/path_pcep_lib.c
pathd/subdir.am

- This is needed due to https://github.com/FRRouting/frr/pull/5451/

Allow FRR to create and manage PCEPlib pthreads

---

bgpd/bgp_routemap.c

Signed-off-by: GalaxyGorilla <sascha@netdef.org>

bgp: remove unneccessary setting of peers

---

pathd/path_nb_config.c

Signed-off-by: GalaxyGorilla <sascha@netdef.org>

pathd: fix heap use after deletion

---

bgpd/bgp_nexthop.c
bgpd/bgp_nexthop.h
bgpd/bgp_nht.c

since the addition of srte_color to the comparison for bgp nexthops
it is possible to have several nexthops per prefix but since zebra
only stores a per prefix registration we should not unregister for
nh notifications for a prefix until all the nexthops for that prefix
have been deleted. Otherwise we can get into a deadlock situation
where BGP thinks we have registered but we have unregistered from zebra.
Signed-off-by: Pat Ruddy <pat@voltanet.io>

bgpd: do not unregister for prefix nexthop updates if nh exists

---

pathd/path_pcep_lib.c

- The FRR timer thread_cancel_async cancellation function
ends up blocking on a cond_var that never gets notified,
causing the entire pcc to block.
- This is a work-around until we find a solution for the
FRR timers problem.

Use PCEPlib timers instead of FRR timers for now

---

pathd/path_pcep.h
pathd/path_pcep_cli.c

Add pathd PCC delegation-timeout CLI

---

pathd/path_pcep.c
pathd/path_pcep_pcc.c

Removed some compilation warning too.

pathd: pcep module: prevent any possible disconnection race leading to NULL sessions

---

pathd/path_pcep.h
pathd/path_pcep_cli.c
pathd/path_pcep_controller.c
pathd/path_pcep_controller.h
pathd/path_pcep_debug.c
pathd/path_pcep_pcc.c
pathd/path_pcep_pcc.h

Signed-off-by: Javier Garcia <javier.garcia@voltanet.io>

Support for multiple pce's (rebased)

---

pathd/path_pcep_lib.c

Fix minor build warnings

---

pathd/path_pcep_cli.c
pathd/path_pcep_controller.c
pathd/path_pcep_controller.h
pathd/path_pcep_pcc.c
pathd/path_pcep_pcc.h

- Multi-PCE functions that work on pcc_state
have been moved to path_pcep_pcc.c

Improve Multi-PCE encapsulation

---

pathd/path_pcep.c
pathd/path_pcep.h
pathd/path_pcep_cli.c

- Fixed crash in no pcc-peer if it was in use
by a pcc and then removed with no peer
- Normalized the pcc optional values
- Added show pcc to show the currently configured
pcc optional values

Improvements to the PCEP CLI

---

pathd/path_pcep_cli.c

- it should be less than state-timeout interval

Change delegation-timeout default

---

pathd/path_pcep_controller.c
pathd/path_pcep_pcc.c

1.- Restore timer proper functionality
2.- In the EV_SYNC_PATH handle use get_best_pce as it's already
calculated either for adding pce's or for a new best after lost
current best.
Signed-off-by: Javier Garcia <javier.garcia@voltanet.io>

Fix multi pce

---

pathd/path_pcep_cli.c
pathd/path_pcep_controller.c
pathd/path_pcep_controller.h

- disconnect and connect again from one or all PCEs
- this does not affect the running-config

pathd: pcep: clear pcep-session vtysh command

---

test_bgp_sender_as_path_loop_detection.py

Signed-off-by: Nathan Mangar <nathan@thundergear.io>
Co-authored-by: Bruno Bernard <contact.brunobernard@gmail.com>
**Test Output** 
```
➜  basetato4 git:(bgp-sender-as-path-loop-detection) ✗ ./run_userns.sh --frr-builddir=/root/buildfrr/ --log-cli-level=DEBUG -v -v  -x test_bgp_sender_as_path_loop_detection.py
=============================================================================================== topotato initialization ===============================================================================================
------------------------------------------------------------------------------------------------ live log sessionstart ------------------------------------------------------------------------------------------------
DEBUG    topotato:topolinux.py:88 executable unshare …
```

topotato: test_bgp_sender_as_path_loop_detection.py

---

test_bgp_extended_optional_parameters_length.py

**Test Output** 
```
➜  basetato4 git:(bgp-extended-optional-parameters-length) ✗ ./run_userns.sh --frr-builddir=/root/buildfrr/ --log-cli-level=DEBUG -v -v  -x test_bgp_extended_optional_parameters_length.py
===================================================================================================== topotato initialization ======================================================================================================
------------------------------------------------------------------------------------------------------ live log sessionstart -------------------------------------------------------------------------------------------------------
DEBUG    topotato:topolinux.py:88 executable unshare found: /usr/bin/unshare
DEBUG    topotato:topolinux.py:88 executable nsenter …
```

topotato: test_bgp_extended_optional_parameters_length.py

---

test_disable_addpath_rx.py

Signed-off-by: Nathan Mangar <nathan@thundergear.io>
Co-authored-by: Bruno Bernard <contact.brunobernard@gmail.com>
**Test Output** 
```
➜  basetato4 git:(bgp-disable-addpath-rx) ✗ ./run_userns.sh --frr-builddir=/root/buildfrr/ --log-cli-level=DEBUG -v -v  -x test_disable_addpath_rx.py
===================================== topotato initialization ======================================
-------------------------------------- live log sessionstart ---------------------------------------
DEBUG    topotato:topolinux.py:88 executable unshare found: /usr/bin/unshare
DEBUG    topotato:topolinux.py:88 executable nsenter found: /usr/bin/nsenter
DEBUG    topotato:topolinux.py:88 executable tini found: /usr/bin/tini
DEBUG    topotato:topolinux.py:88 executable ip found: /usr/sbin/ip
DEBUG …
```

topotato: test_disable_addpath_rx.py

---

test_bgp_aspath_zero.py

**Test Output** 
```
➜  basetato4 git:(bgp-aspath-zero) ✗    ./run_userns.sh --frr-builddir=/root/buildfrr/ --log-cli-level=DEBUG -v -v  -x test_bgp_aspath_zero.py
================================================= topotato initialization =================================================
-------------------------------------------------- live log sessionstart --------------------------------------------------
DEBUG    topotato:topolinux.py:88 executable unshare found: /usr/bin/unshare
DEBUG    topotato:topolinux.py:88 executable nsenter found: /usr/bin/nsenter
DEBUG    topotato:topolinux.py:88 executable tini found: /usr/bin/tini
DEBUG    topotato:topolinux.py:88 executable ip found: /usr/sbin/ip
DEBUG    topotato:frr.py:145 FRR build directory: '/root/buildfrr'
DEBUG …
```

topotato: test_bgp_aspath_zero.py

---

test_bgp_max_med_on_startup.py
topotato/generatorwrap.py

Test output:
```
➜  basetato4 git:(bgp-max-med-on-startup) ✗ ./run_userns.sh --frr-builddir=/root/buildfrr/ --log-cli-level=DEBUG -v -v  -x test_bgp_max_med_on_startup.py
==================================================================================== topotato initialization ====================================================================================
------------------------------------------------------------------------------------- live log sessionstart -------------------------------------------------------------------------------------
DEBUG    topotato:pretty.py:145 executable dot found: /usr/bin/dot
DEBUG    topotato:core.py:160 FRR build directory: '/root/buildfrr/'
DEBUG    topotato:core.py:182 FRR source directory: '/root/buildfrr'
INFO     topotato:core.py:226 FRR …
```

topotato: test_bgp_max_med_on_startup.py
